server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass http://nuvio-painel-api:8000;
        proxy_set_header Host $host;
        client_max_body_size 32k;
    }
    location / {
        try_files $uri $uri/ =404;
    }
}
