// GERADO A MAO, mantido ordenado por BYTES UTF-8 (o que strcmp compara).
// Chave = o portugues que esta no codigo. Ver idioma.h.
  { "  ·  %d título", "  ·  %d title" },
  { "  ·  %d títulos", "  ·  %d titles" },
  { " carregados", " loaded" },
  { " · Nascido em %s", " · Born %s" },
  { "\"Mais como este\"", "\"More like this\"" },
  { "%.1f MB em %d imagens", "%.1f MB in %d images" },
  { "%d %s · OK para explorar", "%d %s · OK to explore" },
  { "%d MINUTOS RESTANTES", "%d MINUTES LEFT" },
  { "%d canais · %d categorias · segure %s para pular seção", "%d channels · %d categories · hold %s to jump sections" },
  { "%d curtidas", "%d likes" },
  { "%d de %d", "%d of %d" },
  { "%d de %d dias ativos no mês", "%d of %d active days this month" },
  { "%d de %d episódios", "%d of %d episodes" },
  { "%d de %s de %c%c%c%c", "%d %s %c%c%c%c" },
  { "%d de 8", "%d of 8" },
  { "%d dias ativos no ano", "%d active days this year" },
  { "%d dias ativos · %d dias seguidos no mês", "%d active days · %d-day streak this month" },
  { "%d min restantes", "%d min left" },
  { "%d na fila", "%d queued" },
  { "%d reproduções", "%d plays" },
  { "%d reproduções  ·  %s", "%d plays  ·  %s" },
  { "%d reproduções registradas", "%d plays recorded" },
  { "%d títulos%s  ·  %s", "%d titles%s  ·  %s" },
  { "%d/10   %d curtidas", "%d/10   %d likes" },
  { "%dh %dmin Restantes", "%dh %dmin left" },
  { "%dh Restantes", "%dh left" },
  { "%dmin Restantes", "%dmin left" },
  { "%s  ·  %d de %d", "%s  ·  %d of %d" },
  { "%s T%dE%d", "%s S%dE%d" },
  { "%s assistidos", "%s watched" },
  { "%s por reprodução", "%s per play" },
  { "%s · %d reproduções", "%s · %d plays" },
  { "%s · nova: %s", "%s · new: %s" },
  { "+ põe um título na sua lista para você achar de novo sem procurar. Ele não marca nada como assistido.", "+ puts a title on your list so you can find it again without searching. It doesn't mark anything as watched." },
  { "0 a %d por dia", "0 to %d per day" },
  { "1080p", "1080p" },
  { "4K (experimental)", "4K (experimental)" },
  { "A SEGUIR", "UP NEXT" },
  { "A aba \"Mais como este\" passa a usar as recomendações do TMDB.", "The \"More like this\" tab uses TMDB recommendations instead." },
  { "A aba de coleção/saga (as outras partes da franquia) na página do filme.", "The collection/saga tab (the other parts of the franchise) on the movie page." },
  { "A aparência dos cartazes em toda a interface: foco, profundidade, largura e arredondamento.", "How posters look everywhere: focus, depth, width and rounding." },
  { "A barra de navegação da esquerda fica sempre aberta, ou recolhida até você ir até ela.", "The left navigation bar stays open, or stays collapsed until you move onto it." },
  { "A chave vem da sua conta Nuvio ou do arquivo do pacote. Não dá para digitar nesta TV.", "The key comes from your Nuvio account or the package file. It cannot be typed on this TV." },
  { "A fileira de retomada, com o que você deixou pela metade e o próximo episódio das séries que acompanha.", "The resume row: what you left unfinished and the next episode of the shows you follow." },
  { "A fileira de retomada: de onde ela vem, que card usa e como ordena o que você deixou pela metade.", "The resume row: where it comes from, which card it uses and how it orders what you left unfinished." },
  { "A fileira de trailers da página do título. Desligue para esconder os cards.", "The trailers row on the title page. Turn off to hide the cards." },
  { "A forma desta fileira não é escolhida aqui.", "This row's shape is not chosen here." },
  { "A forma desta fileira vem de Estilo do \"Continuar assistindo\".", "This row's shape comes from Continue watching style." },
  { "A forma do card da retomada: quadrado com a arte, deitado largo, ou o cartaz em pé.", "The shape of the resume card: square with the artwork, wide landscape, or the upright poster." },
  { "A lista desta TV recebe o título nos dois casos. Isto decide se ele também vai para o Trakt.", "This TV's list gets the title either way. This decides whether it also goes to Trakt." },
  { "A página não expôs as linhas do log. O log completo continua no console do navegador.", "The page did not expose the log lines. The full log is still in the browser console." },
  { "A seguir", "Up next" },
  { "A seguir em %d s", "Up next in %d s" },
  { "A tela de um filme ou série: spoilers dos episódios, botão de trailer e de onde vêm os dados.", "The page for a film or show: episode spoilers, the trailer button, and where the data comes from." },
  { "AGORA", "NOW" },
  { "AO VIVO", "LIVE" },
  { "ARQUIVO", "FILE" },
  { "ATUALIZAÇÃO DISPONÍVEL", "UPDATE AVAILABLE" },
  { "Abra Fontes para escolher outra opção ou recarregar.", "Open Sources to pick another option or reload." },
  { "Abra um filme ou série e escolha Adicionar à lista para guardar.", "Open a movie or show and choose Add to library to keep it." },
  { "Abre a lista de addons da sua conta, para ligar e desligar cada um nesta TV.", "Opens your account's add-on list, to turn each one on or off on this TV." },
  { "Abre a lista de fileiras para reordenar, ligar, desligar e escolher o card de cada uma. A escolha vale só nesta TV.", "Opens the row list to reorder, enable, disable and pick each one's card. The choice applies to this TV only." },
  { "Abre a lista de fileiras para reordenar, ligar, desligar e escolher o card de cada uma. É lá que dá para ver de onde cada fileira vem.", "Opens the row list to reorder, enable, disable and pick each row's card. It is also where you can see where each row comes from." },
  { "Abre uma tela", "Opens a screen" },
  { "Abrindo fonte", "Opening source" },
  { "Acrescenta \"Filme\" ou \"Série\" ao título da fileira, para separar as duas versões do mesmo catálogo.", "Adds \"Film\" or \"Show\" to the row title, to tell apart the two versions of the same catalog." },
  { "Acrescenta o nome do addon ao título da fileira, para separar dois catálogos com o mesmo nome.", "Adds the add-on's name to the row title, to tell apart two catalogs with the same name." },
  { "Addon", "Add-on" },
  { "Addons", "Add-ons" },
  { "Adicionada à Home", "Added to Home" },
  { "Adicionando à biblioteca...", "Adding to library..." },
  { "Adicionar à biblioteca", "Add to library" },
  { "Agrupado por addon · OK: lista alfabética", "Grouped by add-on · OK: alphabetical list" },
  { "Agrupar por addon", "Group by add-on" },
  { "Aguardando a autorização…", "Waiting for authorization…" },
  { "Ajusta a largura dos pôsteres nas fileiras que usam o tamanho personalizável.", "Sets the poster width on rows that use the custom size." },
  { "Ajustar altura", "Fit height" },
  { "Ajustar largura", "Fit width" },
  { "Ajustes", "Settings" },
  { "Ajustes  ·  Fileiras da Home  ·  Limite de fileiras", "Settings  ·  Home rows  ·  Row limit" },
  { "Alemão", "German" },
  { "Alfabética · OK: agrupar por addon", "Alphabetical · OK: group by add-on" },
  { "Amarelo", "Yellow" },
  { "Ambas", "Both" },
  { "Amigo", "Friend" },
  { "Amigos assistindo", "Friends watching" },
  { "Andar de lado numa fileira não espera a animação terminar. Serve para controle que repete rápido.", "Moving sideways in a row no longer waits for the animation. Useful for remotes that repeat quickly." },
  { "Animação", "Animation" },
  { "Animações", "Animations" },
  { "Ano: mais recentes", "Year: newest first" },
  { "Ao mudar, as fileiras são remontadas para os títulos saírem no idioma novo.", "On change, the rows are rebuilt so titles come back in the new language." },
  { "Ao pausar, sobe uma ficha com a sinopse e os dados do que você está vendo.", "On pause, a panel rises with the synopsis and details of what you are watching." },
  { "Aparece também nos apps e no site que leem essa conta.", "It also shows up in the apps and on the website that read that account." },
  { "Aperte + em um filme ou série e ele aparece aqui.", "Press + on a movie or series and it shows up here." },
  { "Aperte Voltar de novo para sair do aplicativo", "Press Back again to exit the app" },
  { "Aperte o botão vermelho do controle para abrir e fechar o registro. No controle da LG ele fica na fileira de botões coloridos, quando o controle tiver essa fileira.", "Press the red button on the remote to open and close the log. On LG remotes it is in the row of coloured buttons, when the remote has that row." },
  { "Aperte o botão vermelho do controle para abrir e fechar o registro. Nos controles Samsung novos o vermelho não é um botão: aperte (ou segure) o botão de números e cores, abaixo do liga-desliga, até a fileira de cores aparecer na tela.", "Press the red button on the remote to open and close the log. On newer Samsung remotes red is not a button: press (or hold) the numbers-and-colours button below the power key until the colour row appears on screen." },
  { "Aplicar", "Apply" },
  { "Aponte a câmera do celular para o código:", "Point your phone camera at the code:" },
  { "Arredondamento", "Corner radius" },
  { "Arte indisponível", "Artwork unavailable" },
  { "Arte localizada", "Localized artwork" },
  { "As %d primeiras ligadas aparecem na Home", "The first %d enabled ones appear on Home" },
  { "As fileiras aparecem aqui depois que o app lê os catálogos dos seus addons. Abra a Home, espere o catálogo carregar e volte a esta tela.", "Rows show up here after the app reads your add-ons' catalogs. Open Home, wait for the catalog to load and come back to this screen." },
  { "Assistido", "Watched" },
  { "Assistir do começo", "Play from beginning" },
  { "Ative Continuar assistindo para ajustar os cards de retomada.", "Turn on Continue Watching to adjust the resume cards." },
  { "Ative Efeito de profundidade para personalizar este detalhe.", "Turn on Depth effect to customise this detail." },
  { "Ative Expandir pôster ao focar para ajustar o tempo de espera.", "Turn on Expand poster on focus to adjust the delay." },
  { "Ative MDBList para escolher as fontes de nota.", "Turn on MDBList to choose the rating sources." },
  { "Ative Miniatura do episódio para desfocar a imagem do próximo episódio.", "Turn on Episode thumbnail to blur the next episode's image." },
  { "Ative Mostrar destaque para exibir os catálogos no topo da Home.", "Turn on Show spotlight to display catalogs at the top of the Home screen." },
  { "Ative TMDB para ajustar o que ele enriquece.", "Turn on TMDB to adjust what it enriches." },
  { "Ative a barra lateral moderna para usar o desfoque.", "Turn on the modern sidebar to use the blur." },
  { "Ative fileiras em Ajustes, na categoria Fileiras da Home.", "Enable rows in Settings, under Home rows." },
  { "Atividade diária indisponível", "Daily activity unavailable" },
  { "Atividade privada ou não compartilhada", "Private or unshared activity" },
  { "Atividade recente", "Recent activity" },
  { "Atraso", "Delay" },
  { "Atraso da expansão", "Expansion delay" },
  { "Atualizando biblioteca...", "Updating library..." },
  { "Atualizando histórico sem interromper o conteúdo anterior…", "Refreshing history without dropping what is already shown…" },
  { "Atualizando · atividade anterior preservada", "Refreshing · previous activity kept" },
  { "Atualizando: addons, coleções e fileiras — a Home se refaz uma vez, no fim", "Refreshing: add-ons, collections and rows — Home rebuilds once, at the end" },
  { "Atualizar tudo", "Refresh everything" },
  { "Atualização indisponível · mostrando atividade anterior", "Refresh unavailable · showing previous activity" },
  { "Atualização indisponível · mostrando atividade anterior · OK: tentar novamente", "Update unavailable · showing previous activity · OK: try again" },
  { "Atualização indisponível · mostrando o último resumo recebido. %s", "Refresh unavailable · showing the last summary received. %s" },
  { "Até aqui (%d episódio)", "Up to here (%d episode)" },
  { "Até aqui (%d episódios)", "Up to here (%d episodes)" },
  { "Automática", "Automatic" },
  { "Automático", "Automatic" },
  { "Autorizado. Entrando…", "Authorized. Signing in…" },
  { "Avaliações", "Ratings" },
  { "Avaliações do Trakt", "Trakt ratings" },
  { "Avaliações gerais", "Overall ratings" },
  { "Aventura", "Adventure" },
  { "Azul", "Blue" },
  { "Azul volta na hora", "Blue restores instantly" },
  { "Azul ártico", "Arctic blue" },
  { "Azul: tela cheia · Voltar: fechar", "Blue: full screen · Back: close" },
  { "Ação", "Action" },
  { "Barra lateral", "Sidebar" },
  { "Barra lateral e destaque", "Sidebar and spotlight" },
  { "Barra lateral moderna", "Modern sidebar" },
  { "Biblioteca", "Library" },
  { "Biblioteca atualizada", "Library updated" },
  { "Biografia", "Biography" },
  { "Boas histórias conectam.", "Good stories connect people." },
  { "Borda", "Edge" },
  { "Botão", "Button" },
  { "Botão de trailer", "Trailer button" },
  { "Branco", "White" },
  { "Brilho da borda", "Edge glow" },
  { "Busca", "Search" },
  { "Busca dados de episódios no TMDB para complementar os que vêm do addon.", "Fetches episode data from TMDB to complement what the add-on provides." },
  { "Buscando fontes nos addons…", "Looking for sources in your addons…" },
  { "Buscando seus addons e o que você estava assistindo.", "Fetching your add-ons and what you were watching." },
  { "Buscar filmes e séries", "Search movies and TV shows" },
  { "CANCELADA", "CANCELED" },
  { "CH+ e CH− zapeiam no canto", "CH+ and CH− zap in the corner" },
  { "COLEÇÃO", "COLLECTION" },
  { "COLEÇÕES", "COLLECTIONS" },
  { "Cabe %d fileira a mais aqui", "Room for %d more row here" },
  { "Cabem %d fileiras a mais aqui", "Room for %d more rows here" },
  { "Cada perfil tem sua própria lista e seu progresso.", "Each profile has its own list and its own progress." },
  { "Canais", "Channels" },
  { "Canal", "Channel" },
  { "Canal ao vivo, sem grade de programação", "Live channel, no schedule" },
  { "Canal em miniatura", "Picture in picture" },
  { "Carmesim", "Crimson" },
  { "Carregando arte…", "Loading artwork…" },
  { "Carregando atividade…", "Loading activity…" },
  { "Carregando canais…", "Loading channels…" },
  { "Carregando comentários…", "Loading comments…" },
  { "Carregando episódios…", "Loading episodes…" },
  { "Carregando histórico…", "Loading history…" },
  { "Carregando os perfis da sua conta…", "Loading your account profiles…" },
  { "Carregando programação…", "Loading schedule…" },
  { "Carregando títulos…", "Loading titles…" },
  { "Cartaz em pé", "Portrait poster" },
  { "Cartazes", "Artwork" },
  { "Categoria", "Category" },
  { "Categorias  ·  OK entra na categoria escolhida", "Categories  ·  OK enters the selected category" },
  { "Catálogo", "Catalog" },
  { "Catálogo de um addon. Cada fileira destas é um pedido pela rede quando a Home monta.", "A catalog from an add-on. Each of these rows is one network request when the Home screen builds." },
  { "Catálogo organizado por serviço", "Catalog organized by service" },
  { "Catálogos do destaque", "Hero catalogs" },
  { "Chave da API", "API key" },
  { "Chinês", "Chinese" },
  { "Cima/baixo: seções  ·  Voltar: menu", "Up/down: sections  ·  Back: menu" },
  { "Classificação", "Rating" },
  { "Cobertura da borda", "Edge coverage" },
  { "Cobertura: período selecionado", "Coverage: selected period" },
  { "Coleção", "Collection" },
  { "Coleções e sagas", "Collections and sagas" },
  { "Comentários", "Comments" },
  { "Como a retomada se ordena: pelo mais recente, no estilo dos streamings, ou com os episódios futuros num bloco separado.", "How the resume row is ordered: most recent first, streaming style, or with upcoming episodes in their own block." },
  { "Compacto", "Compact" },
  { "Completas", "Full" },
  { "Comédia", "Comedy" },
  { "Conecta a sua conta do Simkl, uma alternativa ao Trakt para acompanhar séries.", "Connects your Simkl account, an alternative to Trakt for tracking shows." },
  { "Conecta a sua conta do Trakt para marcar o que assistiu e usar a sua lista.", "Connects your Trakt account to mark what you have watched and use your list." },
  { "Conectar %s", "Connect %s" },
  { "Conecte o Trakt e assista a um filme ou episódio. Seu resumo usa somente o histórico disponível.", "Connect Trakt and watch a movie or episode. This summary only uses the history that is available." },
  { "Conhecido por  %s", "Known for  %s" },
  { "Conta", "Account" },
  { "Conta Nuvio", "Nuvio account" },
  { "Conteúdo Assustador", "Frightening Content" },
  { "Conteúdo da Home", "Home content" },
  { "Continuar", "Continue" },
  { "Continuar assistindo", "Continue Watching" },
  { "Continuar no canto", "Keep it in the corner" },
  { "Contorno", "Outline" },
  { "Controla o arredondamento dos cantos dos pôsteres.", "Controls how rounded the poster corners are." },
  { "Cor", "Color" },
  { "Cor de destaque", "Accent color" },
  { "Cor do anel que marca onde está o foco. É a mesma escolha de tema do app web, e vale só para o anel: o resto da interface não muda de cor.", "Color of the ring that marks where the focus is. It is the same theme choice as the web app, and it applies to the ring only: the rest of the interface does not change color." },
  { "Coreano", "Korean" },
  { "Curta", "Short" },
  { "DESMARCAR COMO ASSISTIDO", "MARK AS UNWATCHED" },
  { "DIAS ATIVOS", "ACTIVE DAYS" },
  { "DIRETORES", "DIRECTORS" },
  { "Da conta", "From account" },
  { "Da interface", "Interface language" },
  { "Data de lançamento completa", "Full release date" },
  { "Datas de estreia e classificação etária do seu país, pelo TMDB.", "Release dates and age rating for your country, from TMDB." },
  { "Datas de lançamento", "Release dates" },
  { "De onde vem a fileira de retomada. \"Ambas\" usa a conta Nuvio e completa com o Trakt.", "Where the resume row comes from. \"Both\" uses the Nuvio account and fills in from Trakt." },
  { "De onde vem a fileira de retomada. Ambas usa a conta e completa com o Trakt.", "Where the resume row comes from. Both uses the account and fills in from Trakt." },
  { "Define a preferência de resolução. A disponibilidade depende das fontes do addon.", "Sets the resolution preference. Availability depends on the add-on's sources." },
  { "Depois ele fica no menu lateral, no ícone de grade.", "After that it lives in the side menu, on the grid icon." },
  { "Depois, o botão AZUL abre sua lista quando quiser.", "The BLUE button opens your list whenever you want." },
  { "Depois, o botão CANAL + abre sua lista quando quiser.", "The CHANNEL + button opens your list whenever you want." },
  { "Desative a barra lateral moderna para escolher entre recolhida e fixa.", "Turn off the modern sidebar to choose between collapsed and pinned." },
  { "Descubra o que seus amigos estão vendo.\nUma nova recomendação pode começar aqui.", "See what your friends are watching.\nYour next pick could start here." },
  { "Desenha a interface em 4K nas TVs que permitem. Muitas ignoram o pedido e continuam em 1080p — o log diz qual é o caso. Vale reiniciar o app depois de mudar. O vídeo já é 4K nos dois casos.", "Draws the interface in 4K on TVs that allow it. Many ignore the request and stay at 1080p — the log says which. Worth restarting the app after changing it. Video is already 4K either way." },
  { "Desfoca a arte atrás da barra lateral moderna em vez de usar um fundo sólido.", "Blurs the artwork behind the modern sidebar instead of using a solid background." },
  { "Desfocar não assistidos", "Blur unwatched" },
  { "Desfocar próximo episódio", "Blur next episode" },
  { "Desfoque da barra moderna", "Modern sidebar blur" },
  { "Desligada", "Off" },
  { "Desligado", "Off" },
  { "Desmarcado como assistido", "Marked as unwatched" },
  { "Desmarcando como assistido...", "Marking as unwatched..." },
  { "Desmarcar como assistido", "Mark as unwatched" },
  { "Desmarcar este episódio", "Unmark this episode" },
  { "Destaque largo", "Wide feature" },
  { "Detalhes", "Details" },
  { "Detalhes do Filme", "Movie details" },
  { "Dia %d: %u reproduções", "Day %d: %u plays" },
  { "Digite ao menos 2 letras de um filme ou série.", "Type at least 2 letters of a movie or show." },
  { "Dinamarquês", "Danish" },
  { "Direita: resultados   •   Voltar: menu", "Right: results   •   Back: menu" },
  { "Diretor", "Director" },
  { "Direção", "Directed by" },
  { "Direção e Elenco", "Cast & Crew" },
  { "Do app", "From the app" },
  { "Documentário", "Documentary" },
  { "Dom", "Sun" },
  { "Dourado", "Gold" },
  { "Drogas/Álcool", "Drugs/Alcohol" },
  { "Duração", "Runtime" },
  { "Dá relevo aos cartazes: borda iluminada e um reflexo que acompanha o foco.", "Gives posters relief: a lit edge and a sheen that follows the focus." },
  { "EM EXIBIÇÃO", "AIRING" },
  { "ENTRE AMIGOS", "AMONG FRIENDS" },
  { "EPISÓDIO %d", "EPISODE %d" },
  { "EPISÓDIOS", "EPISODES" },
  { "Efeito de Profundidade", "Depth effect" },
  { "Efeito de profundidade", "Depth effect" },
  { "Elenco", "Cast" },
  { "Elenco e equipe", "Cast and crew" },
  { "Em Tipo, escolha Todos. Confira também os filtros em Ajustes.", "Under Type, choose All. Check the filters in Settings too." },
  { "Em alta", "Trending" },
  { "Enriquecer \"Continuar assistindo\"", "Enrich \"Continue Watching\"" },
  { "Entrar na sua conta", "Sign in to your account" },
  { "Entre amigos", "Among friends" },
  { "Episódio", "Episode" },
  { "Episódio %d", "Episode %d" },
  { "Episódios", "Episodes" },
  { "Episódios indisponíveis. Selecione a temporada e pressione OK para tentar novamente.", "Episodes unavailable. Pick the season and press OK to try again." },
  { "Escolha a categoria e entre nela. Cima e baixo trocam de categoria em vez de linha em linha.", "Pick a category and go into it. Up and down move between categories instead of line by line." },
  { "Escolhe o próximo episódio a partir do mais avançado marcado como assistido.", "Picks the next episode from the furthest one marked as watched." },
  { "Esconde das fileiras o que ainda não estreou. Título sem fonte nenhuma ocupa lugar e não abre.", "Hides what has not been released yet. A title with no source takes up a slot and will not open." },
  { "Escreve a data de estreia por extenso em vez de só o ano.", "Writes the release date in full instead of just the year." },
  { "Escreve o nome do título abaixo do cartaz. A maior parte da arte já traz o nome impresso.", "Writes the title under the poster. Most artwork already has the name printed on it." },
  { "Escuro 100%", "Dark 100%" },
  { "Escuro 25%", "Dark 25%" },
  { "Escuro 50%", "Dark 50%" },
  { "Escuro 75%", "Dark 75%" },
  { "Esmeralda", "Emerald" },
  { "Espanhol", "Spanish" },
  { "Especiais", "Specials" },
  { "Esporte", "Sport" },
  { "Esta versão manda o log para o terminal, não para um arquivo. Para ler aqui, rode com NUVIO_LOG apontando para um arquivo.", "This build sends the log to the terminal, not to a file. To read it here, run with NUVIO_LOG pointing at a file." },
  { "Estado", "Status" },
  { "Estado da última troca de dados com a sua conta: addons, progresso, coleções e preferências.", "State of the last exchange with your account: add-ons, progress, collections and preferences." },
  { "Este episódio", "This episode" },
  { "Este pacote foi montado sem servidor.", "This package was built without a server." },
  { "Esticar", "Stretch" },
  { "Estilo", "Style" },
  { "Estilo do \"Continuar assistindo\"", "\"Continue Watching\" style" },
  { "Estilo streaming", "Streaming style" },
  { "Estúdios", "Studios" },
  { "Expandir pôster ao focar", "Expand poster on focus" },
  { "FILMOGRAFIA", "FILMOGRAPHY" },
  { "FINALIZADA", "ENDED" },
  { "Faixa", "Track" },
  { "Faixa de áudio escolhida quando o arquivo tem mais de uma. Se o idioma não existir no arquivo, o player usa a primeira.", "Which audio track is picked when the file has more than one. If the language is not in the file, the player uses the first." },
  { "Faixas de áudio", "Audio tracks" },
  { "Família", "Family" },
  { "Fantasia", "Fantasy" },
  { "Favoritos", "Favorites" },
  { "Fechar", "Close" },
  { "Fechar o vídeo", "Close the video" },
  { "Fica guardada nesta TV. O que você salvar no celular continua chegando aqui pela sua conta.", "Kept on this TV. What you save on your phone still arrives here through your account." },
  { "Ficha técnica", "Details" },
  { "Ficção científica", "Science Fiction" },
  { "Fileira", "Row" },
  { "Fileira montada pelo próprio app com o que você já assistiu ou salvou. Não vem de addon nenhum.", "A row the app builds itself from what you have watched or saved. It comes from no add-on." },
  { "Fileiras da Home", "Home rows" },
  { "Filme", "Movie" },
  { "Filmes", "Movies" },
  { "Filmes %.0f%%  ·  Episódios %.0f%%", "Movies %.0f%%  ·  Episodes %.0f%%" },
  { "Filmografia", "Filmography" },
  { "Filmografia em ordem cronológica", "Filmography in chronological order" },
  { "Finlandês", "Finnish" },
  { "Fixa", "Pinned" },
  { "Fixo", "Fixed" },
  { "Foco no Pôster", "Poster focus" },
  { "Fonte HDR", "HDR source" },
  { "Fonte HDR10", "HDR10 source" },
  { "Fonte HDR10+", "HDR10+ source" },
  { "Fonte OpenSubtitles", "OpenSubtitles source" },
  { "Fonte do \"Continuar assistindo\"", "Source for \"Continue Watching\"" },
  { "Fontes", "Sources" },
  { "Fontes deste episódio", "Sources for this episode" },
  { "Fora da Home", "Not on Home" },
  { "Fora da Home  %d", "Not on Home  %d" },
  { "Fora da biblioteca", "Not in library" },
  { "Fora do limite", "Beyond the limit" },
  { "Fotos do elenco e nomes dos papéis, vindos do TMDB.", "Cast photos and character names, from TMDB." },
  { "Francês", "French" },
  { "Français", "Français" },
  { "Funciona sozinho", "Works by itself" },
  { "Fundo", "Background" },
  { "Fundo em tela cheia", "Full-screen backdrop" },
  { "Gradiente de foco clássico", "Classic focus gradient" },
  { "Grafite", "Graphite" },
  { "Grande", "Large" },
  { "Grego", "Greek" },
  { "Grupo de coleções: uma pasta de atalhos para catálogos, montada na sua conta.", "A collection group: a folder of catalog shortcuts, built in your account." },
  { "Guia TV", "TV Guide" },
  { "Guia de TV", "TV Guide" },
  { "Guia de canais", "Channel guide" },
  { "GÊNERO", "GENRE" },
  { "Hebraico", "Hebrew" },
  { "História", "History" },
  { "Histórico não consultado", "History not checked" },
  { "Histórico parcial · detalhes no perfil", "Partial history · details in profile" },
  { "Histórico parcial: os totais consideram somente os registros carregados.", "Partial history: the totals count only the records loaded so far." },
  { "Holandês", "Dutch" },
  { "Home cheia (%d de %d) · entrou na fila e sobe quando abrir vaga", "Home is full (%d of %d) · queued, moves up when a slot opens" },
  { "Húngaro", "Hungarian" },
  { "Idioma", "Language" },
  { "Idioma da interface, animações, sua conta, addons, serviços conectados e informações do app.", "Interface language, animation, your account, add-ons, connected services and app information." },
  { "Idioma da legenda", "Subtitle language" },
  { "Idioma de toda a interface. Não muda o idioma das legendas nem do áudio.", "The language of the whole interface. It does not change subtitle or audio language." },
  { "Idioma do áudio", "Audio language" },
  { "Idioma dos metadados", "Metadata language" },
  { "Idioma dos textos que o TMDB traz (sinopse, títulos). \"Da interface\" segue o idioma do app.", "Language of the texts TMDB provides (overview, titles). \"Interface language\" follows the app language." },
  { "Idioma procurado primeiro na lista de legendas de cada título. \"Da conta\" segue o que está no seu perfil.", "The language looked for first in each title's subtitle list. \"From account\" follows your profile." },
  { "Imagem preta com o áudio tocando? Recarrega esta fonte sem HDR nem Dolby Vision.", "Black picture while the audio plays? Reloads this source with no HDR and no Dolby Vision." },
  { "Incorporada", "Embedded" },
  { "Indisponível agora", "Unavailable right now" },
  { "Indonésio", "Indonesian" },
  { "Informação", "Information" },
  { "Inglês", "English" },
  { "Integrações", "Integrations" },
  { "Interface", "Interface" },
  { "Interface e conta", "Interface and account" },
  { "Início", "Home" },
  { "Italiano", "Italian" },
  { "Jade", "Jade" },
  { "Japonês", "Japanese" },
  { "Já na sua lista", "Already on your list" },
  { "Lançamento", "Release" },
  { "Largo", "Wide" },
  { "Largura do item", "Item width" },
  { "Layout da Home", "Home layout" },
  { "Legenda", "Subtitle" },
  { "Legenda %d", "Subtitle %d" },
  { "Legendas", "Subtitles" },
  { "Leve", "Mild" },
  { "Ligada", "On" },
  { "Ligado", "On" },
  { "Limite de %d fileiras — coleções não contam", "Limit of %d rows — collections don't count" },
  { "Limite de fileiras", "Row limit" },
  { "Linguagem Imprópria", "Strong Language" },
  { "Lista as produtoras na página do título; tocar num logo abre os títulos dela.", "Lists the production companies on the title page; selecting a logo opens their titles." },
  { "Lista as redes (HBO, Netflix…) na página da série; tocar num logo abre os títulos dela.", "Lists the networks (HBO, Netflix…) on the series page; selecting a logo opens their titles." },
  { "Lista de prêmios configurada pelo usuário", "Awards list configured by the user" },
  { "Lista do Nuvio", "Nuvio list" },
  { "Local do Descobrir", "Discover location" },
  { "MARCAR COMO ASSISTIDO", "MARK AS WATCHED" },
  { "Mais %d catálogo disponível", "%d more catalog available" },
  { "Mais %d catálogos disponíveis", "%d more catalogs available" },
  { "Mais como este", "More like this" },
  { "Mais vistos", "Most watched" },
  { "Marcado como assistido", "Marked as watched" },
  { "Marcando como assistido...", "Marking as watched..." },
  { "Marcar como assistido", "Mark as watched" },
  { "Marcar este episódio", "Mark this episode" },
  { "Março", "March" },
  { "Memória usada por imagens", "Memory used by images" },
  { "Miniatura do episódio", "Episode thumbnail" },
  { "Mistério", "Mystery" },
  { "Moderado", "Moderate" },
  { "Mostra a nota do IMDb no canto dos cartazes da Home.", "Shows the IMDb rating in the corner of Home posters." },
  { "Mostra na retomada o próximo episódio mesmo antes de ele ir ao ar.", "Shows the next episode in the resume row even before it airs." },
  { "Mostra o botão de trailer na tela do título, quando existe um trailer conhecido.", "Shows the trailer button on the title page when a trailer is known." },
  { "Mostra ou esconde esta fonte na fileira de notas da página do título.", "Shows or hides this source in the ratings row of the title page." },
  { "Mostrar", "Show" },
  { "Mostrar \"Continuar assistindo\"", "Show \"Continue Watching\"" },
  { "Mostrar destaque", "Show hero" },
  { "Mostrar episódios não exibidos", "Show unaired episodes" },
  { "Mostrar na Busca", "Show in Search" },
  { "Música", "Music" },
  { "NO AR AGORA", "ON NOW" },
  { "NOVO NO NUVIO", "NEW IN NUVIO" },
  { "Na Home", "On Home" },
  { "Na Home  %d de %d", "On Home  %d of %d" },
  { "Na TV da LG é o botão vermelho do controle. Se a tela congelar e o vermelho não responder, o botão verde mostra o painel de arranque.", "On the LG TV it is the red button on the remote. If the screen freezes and red does not respond, the green button shows the startup panel." },
  { "Na TV da Samsung o vermelho sai do botão de números e cores, abaixo do liga-desliga.", "On the Samsung TV red comes from the numbers-and-colours button, below the power key." },
  { "Na barra lateral", "In the sidebar" },
  { "Na biblioteca", "In library" },
  { "Na fila", "Queued" },
  { "Nada salvo por enquanto", "Nothing saved yet" },
  { "Nao foi possivel iniciar a consulta. Tente novamente.", "Could not start the search. Try again." },
  { "Navegar rápido", "Fast navigation" },
  { "Navegação horizontal rápida", "Fast horizontal navigation" },
  { "Nenhum", "None" },
  { "Nenhum addon nesta conta.", "No add-ons in this account." },
  { "Nenhum catálogo de canais nos addons instalados.", "No channel catalog in the installed addons." },
  { "Nenhum comentário ainda.", "No comments yet." },
  { "Nenhum destaque neste período.", "Nothing stands out in this period." },
  { "Nenhum título nesta lista.", "No titles in this list." },
  { "Nenhum título neste filtro", "No titles under this filter" },
  { "Nenhum título recebido", "No titles received" },
  { "Nenhuma", "None" },
  { "Nenhuma atividade disponível agora.", "No activity available right now." },
  { "Nenhuma faixa disponível nesta fonte.", "No track available in this source." },
  { "Nenhuma fileira ativa", "No active rows" },
  { "Nenhuma fileira conhecida ainda", "No rows known yet" },
  { "Nenhuma fileira ligada", "No rows enabled" },
  { "Nenhuma fonte direta disponível. Use Recarregar para tentar novamente.", "No direct source available. Use Reload to try again." },
  { "Nenhuma linha de log ainda.", "No log lines yet." },
  { "Nenhuma reprodução neste período", "No plays in this period" },
  { "No celular, abra:", "On your phone, open:" },
  { "Nome do addon no catálogo", "Addon name in catalog" },
  { "Norueguês", "Norwegian" },
  { "Nota da audiência", "Audience score" },
  { "Notas do IMDb", "IMDb ratings" },
  { "Notas do Letterboxd", "Letterboxd ratings" },
  { "Notas do Metacritic", "Metacritic ratings" },
  { "Notas do MyAnimeList", "MyAnimeList ratings" },
  { "Notas do Rotten Tomatoes", "Rotten Tomatoes ratings" },
  { "Notas do TMDB", "TMDB ratings" },
  { "Notas do Trakt", "Trakt ratings" },
  { "Notícias", "News" },
  { "Nudez", "Nudity" },
  { "Nuvio %s", "Nuvio %s" },
  { "Não assistido", "Not watched" },
  { "Não começados", "Not started" },
  { "Não consegui falar com o servidor.", "Could not reach the server." },
  { "Não foi possível abrir a fonte", "Could not open the source" },
  { "Não foi possível atualizar o histórico.", "Could not refresh the history." },
  { "Não foi possível atualizar. Tente novamente.", "Could not update. Try again." },
  { "Não foi possível carregar os perfis. OK: tentar novamente", "Could not load the profiles. OK: try again" },
  { "Não foi possível carregar. OK para tentar novamente.", "Could not load. OK to try again." },
  { "Não foi possível confirmar este resumo agora.", "Could not confirm this summary right now." },
  { "Não pede confirmação: OK sai na hora. Para voltar é preciso entrar de novo pelo QR.", "No confirmation: OK signs out immediately. Getting back in needs the QR code again." },
  { "O MDBList junta notas de várias fontes na página do título. Desligar esconde a fileira inteira.", "MDBList gathers ratings from several sources on the title page. Turning it off hides the whole row." },
  { "O TMDB enriquece títulos com sinopse, elenco com foto, ficha técnica e trailers. Desligar corta tudo isso de uma vez.", "TMDB enriches titles with overview, cast photos, details and trailers. Turning it off removes all of it at once." },
  { "O Trakt não liberou um histórico público para esta conta.", "Trakt did not expose a public history for this account." },
  { "O addon desta coleção não está instalado nesta TV.", "This collection's addon is not installed on this TV." },
  { "O bloco grande no topo da Home, com a arte e o nome de um título em destaque.", "The large block at the top of the Home screen, with one title's artwork and name." },
  { "O botão AZUL devolve a tela cheia instantaneamente — a fonte nunca parou.", "The BLUE button brings it back full screen — the source never stopped." },
  { "O botão Voltar encerra a miniatura quando não quiser mais.", "The Back button ends the mini player when you are done." },
  { "O cartaz em foco cresce e abre a arte deitada atrás dele depois de um instante parado.", "The focused poster grows and reveals the landscape artwork behind it after a moment at rest." },
  { "O destaque do topo ocupa a tela inteira atrás das fileiras, em vez de ficar num bloco.", "The spotlight fills the whole screen behind the rows instead of sitting in a block." },
  { "O feed dos amigos usa o card com o nome de quem assistiu.", "The friends feed uses the card that shows who watched." },
  { "O guia precisa de um addon de canais (como o FrostView TV) instalado na conta.", "The guide needs a channel addon (like FrostView TV) installed on the account." },
  { "O que aparece em cada cartaz", "What each poster shows" },
  { "O que vamos assistir?", "What are we watching?" },
  { "O vídeo fica no canto", "The video stays in the corner" },
  { "OK   Abrir", "OK   Open" },
  { "OK   Alterar o valor", "OK   Change the value" },
  { "OK   Confirmar", "OK   Confirm" },
  { "OK  Adicionar à Home", "OK  Add to Home" },
  { "OK  Agrupar as fileiras por addon\nVoltar  Fechar", "OK  Group rows by addon\nBack  Close" },
  { "OK  Alternar entre agrupado por addon e lista alfabética\nVoltar  Fechar", "OK  Toggle between grouped by add-on and alphabetical\nBack  Close" },
  { "OK  Sincronizar a conta e refazer a Home agora (addons, coleções e fileiras)\nVoltar  Fechar", "OK  Sync the account and rebuild Home now (add-ons, collections and rows)\nBack  Close" },
  { "OK abre. As setas laterais não fazem nada nesta linha.", "OK opens it. Left and right do nothing on this line." },
  { "OK assiste  ·  segure OK = favorito  ·  segure ↑↓ pula seção  ·  Voltar sai", "OK plays  ·  hold OK = favorite  ·  hold ↑↓ jumps sections  ·  Back exits" },
  { "OK ou Voltar para fechar este aviso", "OK or Back to dismiss this notice" },
  { "OK para abrir  ·  Baixo para o player  ·  Voltar para dispensar", "OK to open  ·  Down for the player  ·  Back to dismiss" },
  { "OK para começar", "OK to start" },
  { "OK para começar agora  ·  Baixo para o player  ·  Voltar para ficar", "OK to start now  ·  Down for the player  ·  Back to stay" },
  { "OK para explorar", "OK to explore" },
  { "OK para fechar", "OK to close" },
  { "OK para tentar de novo · Voltar para fechar", "OK to try again · Back to close" },
  { "OK toca na hora. Com o canal no ar, BAIXO ou o botão AZUL abrem o guia por cima do vídeo; CH+ e CH− zapeiam.", "OK plays right away. While a channel is on, DOWN or the BLUE button open the guide over the video; CH+ and CH− zap." },
  { "OK troca de canal  ·  segure OK = favorito  ·  segure ↑↓ pula seção  ·  Voltar ou Azul fecha", "OK switches channel  ·  hold OK = favorite  ·  hold ↑↓ jumps sections  ·  Back or Blue closes" },
  { "OK · Conferir conexão", "OK · Check connection" },
  { "OK · Tentar novamente", "OK · Try again" },
  { "OK · abrir título   ·   Voltar · fechar", "OK · open title   ·   Back · close" },
  { "OK: alterar", "OK: change" },
  { "OK: digitar   •   Voltar: menu", "OK: type   •   Back: menu" },
  { "OK: ligar ou desligar   ·   Voltar: Ajustes", "OK: enable or disable   ·   Back: Settings" },
  { "Oceano", "Ocean" },
  { "Oculta detalhes da miniatura para evitar spoilers de episódios ainda não assistidos.", "Hides thumbnail detail to avoid spoilers for episodes you have not watched." },
  { "Ocultar", "Hide" },
  { "Ocultar não lançados", "Hide unreleased" },
  { "Onde fica a tela Descobrir: junto da Busca, como item próprio na barra lateral, ou em lugar nenhum.", "Where the Discover screen lives: next to Search, as its own sidebar item, or nowhere." },
  { "Onde o + deve salvar?", "Where should + save?" },
  { "Onde o + salva", "Where + saves" },
  { "Onde o relevo é aplicado. Desligar em alguns lugares alivia o desenho sem perder o efeito onde ele importa.", "Where the relief is applied. Turning it off in some places eases drawing without losing the effect where it matters." },
  { "Opacidade", "Opacity" },
  { "Opção indisponível", "Option unavailable" },
  { "Opções do título", "Title options" },
  { "Ordem da lista", "List order" },
  { "Ordem original do ranking", "The ranking's original order" },
  { "Ordenar", "Sort" },
  { "Ordenar e ativar fileiras", "Reorder and enable rows" },
  { "Ordenação", "Sort order" },
  { "Original", "Original" },
  { "Os canais viram um guia", "Your channels become a guide" },
  { "Os filmes e séries da sua coleção no Trakt ficam reunidos nesta aba.", "The movies and shows in your Trakt collection are gathered in this tab." },
  { "Os gêneros aparecem conforme o histórico cresce.", "Genres appear as your history grows." },
  { "Os resultados dos addons aparecem aqui.", "Results from your addons show up here." },
  { "Ouro rosé", "Rose gold" },
  { "PIN de %s", "PIN for %s" },
  { "PIN incorreto", "Wrong PIN" },
  { "PRÊMIOS E CÂNONE", "AWARDS & CANON" },
  { "PULANDO CATEGORIAS", "JUMPING CATEGORIES" },
  { "Padrão", "Default" },
  { "Painel ao pausar", "Pause panel" },
  { "País de Origem", "Country" },
  { "Perfil", "Profile" },
  { "Perfil %d", "Profile %d" },
  { "Perfil e Stats", "Profile & Stats" },
  { "Perfil em uso nesta TV. Trocar de perfil é feito na tela de perfis, ao abrir o app.", "The profile in use on this TV. Switching profiles is done on the profile screen when the app opens." },
  { "Perfil indisponível", "Profile unavailable" },
  { "Perfil indisponível. O último resumo continua seguro, se houver.", "Profile unavailable. Your last summary is still safe, if there is one." },
  { "Perfil privado ou histórico não compartilhado", "Private profile or unshared history" },
  { "Pergunta as fontes de novo a todos os addons.", "Asks every addon for sources again." },
  { "Personalizar", "Customise" },
  { "Período não informado", "Period not given" },
  { "Pessoa · ação · título · horário", "Person · action · title · time" },
  { "PgUp / PgDn  Trocar seção", "PgUp / PgDn  Switch section" },
  { "Pico: %d reproduções no dia %d", "Peak: %d plays on day %d" },
  { "Polonês", "Polish" },
  { "Popular - Filme", "Popular - Movies" },
  { "Popular - Série", "Popular - TV" },
  { "Por categoria, com o que está no ar e o que vem a seguir — a grade vem do EPG, em português.", "By category, with what's on now and what's up next — the schedule comes from the EPG." },
  { "Português", "Portuguese" },
  { "Português (BR)", "Portuguese (BR)" },
  { "Português (Brasil)", "Português (Brasil)" },
  { "Português (Portugal)", "Português (Portugal)" },
  { "Posição", "Position" },
  { "Preenche a ficha técnica da página do título (status, duração, países).", "Fills in the title page details (status, runtime, countries)." },
  { "Prefere a ficha do addon de metadados à do Cinemeta. Útil quando o seu addon tem sinopse e elenco melhores.", "Prefers the metadata add-on's details over Cinemeta's. Useful when your add-on has a better synopsis and cast." },
  { "Prefere pôster e fundo traduzidos pelo TMDB quando o título tem arte no seu idioma.", "Prefers TMDB's localized poster and backdrop when the title has art in your language." },
  { "Preferência para fontes compatíveis. O formato disponível também depende do arquivo e da TV.", "Preference for compatible sources. The available format also depends on the file and the TV." },
  { "Preparando o código…", "Preparing the code…" },
  { "Preparando seu catálogo…", "Getting your catalog ready…" },
  { "Preto", "Black" },
  { "Priorizar metadados externos", "Prefer external metadata" },
  { "Produtoras", "Production companies" },
  { "Profundidade no \"Continuar\"", "Depth on \"Continue\"" },
  { "Profundidade no elenco", "Depth on cast" },
  { "Profundidade nos episódios", "Depth on episodes" },
  { "Profundidade nos pôsteres", "Depth on posters" },
  { "Profundidade nos trailers", "Depth on trailers" },
  { "Programa de TV", "TV Show" },
  { "Progresso salvo", "Progress saved" },
  { "Pronto.", "Done." },
  { "Proporção", "Aspect ratio" },
  { "Próximo", "Next" },
  { "Próximo do episódio mais alto", "Next up from furthest episode" },
  { "Próximo episódio", "Next episode" },
  { "Pular abertura", "Skip intro" },
  { "Pular créditos", "Skip credits" },
  { "Pular resumo", "Skip recap" },
  { "Página de Detalhes", "Detail page" },
  { "Página de detalhes", "Title page" },
  { "Pôster", "Poster" },
  { "Pôsteres e cards", "Posters and cards" },
  { "Pôsteres horizontais", "Landscape posters" },
  { "Qua", "Wed" },
  { "Qualidade da imagem, formatos de áudio e os idiomas preferidos de legenda e áudio.", "Picture quality, audio formats and your preferred subtitle and audio languages." },
  { "Qualidade máxima", "Maximum quality" },
  { "Qualquer addon de canais instalado entra no guia automaticamente — o FrostView e os próximos também.", "Any installed channel add-on joins the guide automatically — FrostView and the next ones too." },
  { "Quantas fileiras a Home monta. Menos fileiras também significam menos catálogos pedidos pela rede, e não fileiras invisíveis.", "How many rows Home builds. Fewer rows also mean fewer catalogs requested over the network, not invisible rows." },
  { "Quantidade de catálogos incluídos no destaque. Esta linha é apenas informativa.", "How many catalogs are in the spotlight. This line is informational only." },
  { "Quanto a borda do cartaz em foco acende.", "How brightly the focused poster's edge lights up." },
  { "Quanto o reflexo passa por cima da arte do cartaz em foco.", "How much the sheen passes over the focused poster's artwork." },
  { "Quanto tempo o foco precisa ficar parado antes de o cartaz expandir.", "How long the focus must rest before the poster expands." },
  { "Que parte da volta do cartaz a borda iluminada percorre.", "How much of the poster's outline the lit edge travels." },
  { "Quem está assistindo?", "Who's watching?" },
  { "Quem gerou o .ipk precisa informar a URL e a chave do projeto.", "Whoever built the .ipk must supply the project URL and key." },
  { "Qui", "Thu" },
  { "RANKING", "RANKING" },
  { "RENOVADA", "RENEWED" },
  { "REPRODUÇÕES", "PLAYS" },
  { "Ranking na ordem original", "Ranking in its original order" },
  { "Recarregar", "Reload" },
  { "Recolhida", "Collapsed" },
  { "Recomendações", "Recommendations" },
  { "Recortar", "Crop" },
  { "Recorte das 100 reproducoes mais recentes do mes. Duracoes informadas pelo Trakt.", "A slice of the 100 most recent plays this month. Durations reported by Trakt." },
  { "Redes e estúdios", "Networks and studios" },
  { "Reduzidas", "Reduced" },
  { "Reflexo", "Sheen" },
  { "Registro do app", "App log" },
  { "Removendo da biblioteca...", "Removing from library..." },
  { "Removendo dos Salvos...", "Removing from Saved..." },
  { "Remover", "Remove" },
  { "Remover da biblioteca", "Remove from library" },
  { "Remover dos Salvos", "Remove from Saved" },
  { "Removida da Home", "Removed from Home" },
  { "Reproduzindo", "Playing" },
  { "Reproduzindo agora", "Now playing" },
  { "Reproduzir", "Play" },
  { "Reproduzir / pausar", "Play / pause" },
  { "Reprodução", "Playback" },
  { "Reproduções", "Plays" },
  { "Resolução da interface", "Interface resolution" },
  { "Restaurar padrão", "Restore default" },
  { "Retomada disponível   %d%%", "Resume available   %d%%" },
  { "Retomada disponível   %d%%   Episódio T%dE%d", "Resume available   %d%%   Episode S%dE%d" },
  { "Retomar", "Resume" },
  { "Retomar agora", "Resume now" },
  { "Ritmo de atividade", "Activity rhythm" },
  { "Romeno", "Romanian" },
  { "Rosa", "Rose" },
  { "Roteirista", "Writer" },
  { "Russo", "Russian" },
  { "Rótulos nos pôsteres", "Poster labels" },
  { "SUA COMUNIDADE", "YOUR COMMUNITY" },
  { "Sai da conta nesta TV e apaga daqui a sessão, os addons e o progresso guardados.", "Signs out on this TV and erases the stored session, add-ons and progress from here." },
  { "Sair da conta", "Sign out" },
  { "Sair do player encolhe o canal para a borda — a imagem e o som continuam.", "Leaving the player shrinks the channel to the edge — picture and sound keep going." },
  { "Salvando com +", "Saving with +" },
  { "Salvando...", "Saving..." },
  { "Salvo agora", "Saved just now" },
  { "Salvo há %d dias", "Saved %d days ago" },
  { "Salvo há %d h", "Saved %dh ago" },
  { "Salvo há %d min", "Saved %d min ago" },
  { "Salvos", "Saved" },
  { "Se isto não sair daqui, confira seus addons na conta.", "If this does not move on, check your add-ons in your account." },
  { "Se não aparecerem, confira a conexão ou tente outro nome.", "If nothing appears, check the connection or try another name." },
  { "Se um título já estiver aberto, a busca de legendas é refeita um instante depois.", "If a title is already open, the subtitle search is redone a moment later." },
  { "Seg", "Mon" },
  { "Segure OK para marcar como assistido", "Hold OK to mark as watched" },
  { "Segure OK para opções", "Hold OK for options" },
  { "Segure para opções", "Hold for options" },
  { "Segure ↑ ou ↓ no guia para pular de categoria; OK segurado marca favorito.", "Hold ↑ or ↓ in the guide to jump categories; hold OK to favorite." },
  { "Seleção de cinema e séries", "A selection of film and TV" },
  { "Seleção do seu catálogo", "A selection from your catalog" },
  { "Sem HDR", "No HDR" },
  { "Sem arte", "No artwork" },
  { "Sem atividade neste período", "No activity in this period" },
  { "Sem atividade pública por enquanto", "No public activity yet" },
  { "Sem conexão. Tente novamente.", "No connection. Try again." },
  { "Sem grade de programação", "No schedule" },
  { "Sem próximos programas", "No upcoming programs" },
  { "Sem pôster", "No poster" },
  { "Separar futuros", "Split upcoming" },
  { "Serviço", "Service" },
  { "Serviço indisponível", "Service unavailable" },
  { "Serviços de metadados: o que o TMDB enriquece na interface e quais fontes de nota o MDBList mostra.", "Metadata services: what TMDB enriches in the interface and which rating sources MDBList shows." },
  { "Setas: dias  ·  Voltar: menu", "Arrows: days  ·  Back: menu" },
  { "Setas: mover  ·  OK: entrar", "Arrows: move  ·  OK: enter" },
  { "Setas: mover  ·  OK: entrar  ·  Voltar: seguir como %s", "Arrows: move  ·  OK: enter  ·  Back: continue as %s" },
  { "Setas: títulos  ·  OK: detalhes", "Arrows: titles  ·  OK: details" },
  { "Seu mapa de gêneros", "Your genre map" },
  { "Severo", "Severe" },
  { "Sex", "Fri" },
  { "Seções", "Sections" },
  { "Siga pessoas no Trakt para descobrir mais.", "Follow people on Trakt to discover more." },
  { "Sincronização", "Sync" },
  { "Sobre", "About" },
  { "Sobre este app", "About this app" },
  { "Solte para abrir opções", "Release to open options" },
  { "Sombra", "Shadow" },
  { "Status", "Status" },
  { "Sua atividade", "Your activity" },
  { "Sua coleção aparece aqui", "Your collection shows up here" },
  { "Sua coleção no Trakt", "Your Trakt collection" },
  { "Sua conta", "Your account" },
  { "Sua lista", "Your list" },
  { "Sua lista para assistir", "Your watchlist" },
  { "Sua próxima sessão começa aqui", "Your next session starts here" },
  { "Sueco", "Swedish" },
  { "Sáb", "Sat" },
  { "Série", "TV Show" },
  { "Séries", "TV Shows" },
  { "T%dE%d", "S%dE%d" },
  { "T%dE%d  ·  %s%s%.22s", "S%dE%d  ·  %s%s%.22s" },
  { "T%dE%d · %d min restantes", "S%dE%d · %d min left" },
  { "T%dE%d · %s", "S%dE%d · %s" },
  { "T%dE%d · retomar", "S%dE%d · resume" },
  { "T%dE%d%s%s", "S%dE%d%s%s" },
  { "TEMA", "THEME" },
  { "TOP 100   ·   Explorar primeiros 10", "TOP 100   ·   Explore the first 10" },
  { "Tailandês", "Thai" },
  { "Tamanho", "Size" },
  { "Tamanho do cartaz", "Poster size" },
  { "Tamanho dos itens", "Item size" },
  { "Tcheco", "Czech" },
  { "Temporada %d", "Season %d" },
  { "Temporada inteira (%d episódio)", "Whole season (%d episode)" },
  { "Temporada inteira (%d episódios)", "Whole season (%d episodes)" },
  { "Tentar de novo", "Try again" },
  { "Ter", "Tue" },
  { "Termina às %s", "Ends at %s" },
  { "Terror", "Horror" },
  { "Tipo", "Type" },
  { "Tipo de conteúdo", "Content type" },
  { "Tirar de Continuar assistindo", "Remove from Continue Watching" },
  { "Todas", "All" },
  { "Todos", "All" },
  { "Trailers", "Trailers" },
  { "Trakt desconectado", "Trakt disconnected" },
  { "Trakt desconectado. Vincule a conta para ver seu perfil.", "Trakt disconnected. Link the account to see your profile." },
  { "Trakt · perfil público", "Trakt · public profile" },
  { "Troca a barra lateral pela versão nova, com ícones maiores. Ela ignora a escolha entre recolhida e fixa.", "Swaps the sidebar for the new one, with larger icons. It ignores the collapsed/pinned choice." },
  { "Trocar de usuário", "Switch user" },
  { "Trocar sem sair do vídeo", "Switch without leaving the video" },
  { "Troque de canal sem sair da home, sem abrir nada.", "Switch channels without leaving home, without opening anything." },
  { "Tudo o que a tela inicial mostra: quais fileiras aparecem, em que ordem, a barra lateral e o destaque do topo.", "Everything the Home screen shows: which rows appear, in what order, the sidebar and the spotlight on top." },
  { "Tudo o que o app conhece já está na Home", "Everything the app knows is already on Home" },
  { "Turco", "Turkish" },
  { "TÍTULO SELECIONADO", "SELECTED TITLE" },
  { "Título e sinopse", "Title and overview" },
  { "Título: A a Z", "Title: A to Z" },
  { "Títulos do gênero no seu catálogo", "Titles of this genre in your catalog" },
  { "Ucraniano", "Ukrainian" },
  { "Um grupo de coleções mostra atalhos para catálogos, não títulos.", "A collection group shows catalog shortcuts, not titles." },
  { "Uma curadoria por tema e atmosfera", "A curation by theme and mood" },
  { "Usa a arte deitada (16:9) no lugar do cartaz em pé nas fileiras que têm as duas.", "Uses the landscape artwork (16:9) instead of the upright poster on rows that have both." },
  { "Usa a imagem do próprio episódio no card, em vez da arte da série.", "Uses the episode's own image on the card instead of the show's artwork." },
  { "Usa o TMDB para preencher os cartazes da fileira de retomada.", "Uses TMDB to fill in the posters of the resume row." },
  { "Usa título e sinopse do TMDB no lugar dos que vieram no catálogo do addon.", "Uses TMDB's title and overview instead of the ones from the add-on catalog." },
  { "Use Reduzidas para movimentos mais discretos ao navegar pela interface.", "Use Reduced for gentler movement as you navigate the interface." },
  { "Use as setas laterais para escolher. A preferência é aplicada ao alterar o valor.", "Use left and right to choose. The preference applies as you change the value." },
  { "Uso atual de memória pelo cache de imagens, não espaço ocupado no armazenamento da TV.", "Memory currently used by the image cache, not space taken on the TV's storage." },
  { "Vale só nesta TV e neste perfil · não altera a Home dos outros aparelhos", "Applies to this TV and this profile only · does not change Home on other devices" },
  { "Vale só nesta TV · não altera a Home dos outros aparelhos", "Applies to this TV only · does not change Home on your other devices" },
  { "Vale só nesta TV. Ao mudar, a fileira é remontada na hora.", "Applies to this TV only. On change, the row is rebuilt right away." },
  { "Vale só nesta TV. Cada fileira a mais é um pedido a mais pela rede quando a Home monta.", "Applies to this TV only. Each extra row is one more network request when the Home screen builds." },
  { "Vale só nesta TV: não altera a Home dos seus outros aparelhos.", "Applies to this TV only: it does not change the Home screen on your other devices." },
  { "Ver detalhes", "View details" },
  { "Ver o registro do app na TV", "View the app log on the TV" },
  { "Ver perfil", "View profile" },
  { "Ver perfil completo", "View full profile" },
  { "Ver tudo", "See all" },
  { "Verde", "Green" },
  { "Vermelho", "Red" },
  { "Versão", "Version" },
  { "Versão do aplicativo. Esta informação não pode ser alterada.", "App version. This information cannot be changed." },
  { "Vietnamita", "Vietnamese" },
  { "Vincule o Trakt para carregar identidade, obras recentes e estatísticas.", "Link Trakt to load identity, recent activity and stats." },
  { "Violeta", "Violet" },
  { "Violência", "Violence" },
  { "Você está assistindo", "You're watching" },
  { "Você está na %s", "You are on %s" },
  { "Você pode mudar isso depois em Ajustes › Interface e conta.", "You can change this later in Settings › Interface and account." },
  { "Volta ao degradê antigo sob o cartaz em foco, no lugar do realce atual.", "Returns to the old gradient under the focused poster, instead of the current highlight." },
  { "Voltar   Confirmar", "Back   Confirm" },
  { "Voltar   Ir para as categorias", "Back   Go to the categories" },
  { "Voltar   Sair dos ajustes", "Back   Leave settings" },
  { "Voltar  Categorias  ·  Voltar de novo  Sair dos ajustes", "Back  Categories  ·  Back again  Leave settings" },
  { "Voltar  Fechar", "Back  Close" },
  { "Voltar Fechar   Aguarde...", "Back Close   Please wait..." },
  { "Voltar fecha de vez", "Back closes it for good" },
  { "Voltar para fechar", "Back to close" },
  { "Voltar retorna ao menu", "Back returns to the menu" },
  { "Vá para a aba \"Fora da Home\" (↑ e depois →) e aperte OK numa fileira para adicioná-la.", "Go to the \"Not on Home\" tab (↑ then →) and press OK on a row to add it." },
  { "Watchlist do Trakt", "Trakt watchlist" },
  { "Zoom cinema", "Cinema zoom" },
  { "Zoom leve", "Slight zoom" },
  { "Zoom ultra", "Ultra zoom" },
  { "a renovacao veio sem token", "the renewal came without a token" },
  { "a sessão do Trakt expirou — conecte de novo", "the Trakt session expired — connect again" },
  { "abril", "April" },
  { "agosto", "August" },
  { "aguardando", "waiting" },
  { "aguardando escolha de perfil", "waiting for a profile to be chosen" },
  { "apagar", "delete" },
  { "app sem configuracao de servidor", "app built without a server" },
  { "assistindo agora", "watching now" },
  { "assistiu", "watched" },
  { "atividade recente", "recent activity" },
  { "ausente", "missing" },
  { "autorizacao negada no Trakt", "authorization denied by Trakt" },
  { "conectado", "connected" },
  { "conectar", "connect" },
  { "conferindo o manifesto…", "checking the manifest…" },
  { "de %s", "from %s" },
  { "definida", "set" },
  { "dezembro", "December" },
  { "dias em sequência", "day streak" },
  { "dias em sequência no mês", "day streak this month" },
  { "e informe o código:", "and enter the code:" },
  { "espaço", "space" },
  { "expirou — reconectar", "expired — reconnect" },
  { "falha ao consultar o Simkl (HTTP %d)", "Simkl query failed (HTTP %d)" },
  { "falha ao trocar o codigo (HTTP %d)", "code exchange failed (HTTP %d)" },
  { "falhou", "failed" },
  { "fevereiro", "February" },
  { "fez check-in", "checked in" },
  { "janeiro", "January" },
  { "julho", "July" },
  { "junho", "June" },
  { "limpar", "clear" },
  { "linhas %d-%d de %d", "lines %d-%d of %d" },
  { "lista", "list" },
  { "listas", "lists" },
  { "maio", "May" },
  { "março", "March" },
  { "nao consegui pedir o codigo (HTTP %d)", "could not request the code (HTTP %d)" },
  { "nao consegui pedir o codigo ao Simkl (HTTP %d)", "could not request the code from Simkl (HTTP %d)" },
  { "nao consegui pedir o codigo ao Trakt (HTTP %d)", "could not request the code from Trakt (HTTP %d)" },
  { "no ar agora", "on now" },
  { "novembro", "November" },
  { "não consegui desenhar o código", "could not draw the code" },
  { "não fornece nada que este app use", "provides nothing this app uses" },
  { "o Simkl invalidou este código", "Simkl rejected this code" },
  { "o Trakt pediu para esperar; tente daqui a pouco", "Trakt asked us to wait; try again shortly" },
  { "o Trakt respondeu sem token", "Trakt answered without a token" },
  { "o código expirou", "the code expired" },
  { "o que vem a seguir", "up next" },
  { "outubro", "October" },
  { "pacote sem a chave do Simkl", "this build has no Simkl key" },
  { "pacote sem as chaves do Trakt", "package built without Trakt keys" },
  { "pacote sem endereco de login configurado", "package built without a login address" },
  { "para retomar", "to resume" },
  { "perfil", "profile" },
  { "preparando…", "preparing…" },
  { "registrou um check-in", "checked in" },
  { "sem conta", "no account" },
  { "sem fio para falar com o Simkl", "no connection to reach Simkl" },
  { "sem fio para falar com o Trakt", "no thread to talk to Trakt" },
  { "sem fio para falar com o servidor", "no connection to reach the server" },
  { "sem fio para sincronizar", "no connection to sync" },
  { "sem rede ao abrir sessao", "no network when opening the session" },
  { "sem sincronizar", "not synced" },
  { "setembro", "September" },
  { "sincronizando…", "syncing…" },
  { "troca de codigo recusada (HTTP %d)", "code exchange refused (HTTP %d)" },
  { "título", "title" },
  { "títulos", "titles" },
  { "verificando…", "checking…" },
  { "Árabe", "Arabic" },
  { "Áudio", "Audio" },
  { "Âmbar", "Amber" },
  { "É o ajuste mais caro desta tela para a TV desenhar. Desligue se a rolagem engasgar.", "This is the most expensive setting on this screen for the TV to draw. Turn it off if scrolling stutters." },
  { "Última atividade: dia %d", "Last activity: day %d" },
  { "← Voltar", "← Back" },
  { "← →   Alterar o valor", "← →   Change the value" },
  { "← →  Trocar de aba\n↓  Voltar à lista\nVoltar  Fechar", "← →  Switch tab\n↓  Back to the list\nBack  Close" },
  { "↑ Voltar aos filtros   ·   Voltar: menu", "↑ Back to filters   ·   Back: menu" },
  { "↑ ↓   Navegar", "↑ ↓   Navigate" },
  { "↑ ↓  Escolher   ·   OK  Aplicar   ·   Voltar  Fechar", "↑ ↓  Choose   ·   OK  Apply   ·   Back  Close" },
  { "↑ ↓  Escolher categoria\nOK ou →  Entrar na categoria\nVoltar  Sair dos ajustes", "↑ ↓  Pick a category\nOK or →  Enter the category\nBack  Leave settings" },
  { "↑ ↓  Escolher fileira\n← →  Trocar de coluna\nOK  Pegar e mover (coluna Fileira) · Ligar, trocar card e tamanho nas outras\nVoltar  Fechar", "↑ ↓  Pick a row\n← →  Switch column\nOK  Grab and move (Row column) · Toggle, change card and size in the others\nBack  Close" },
  { "↑ ↓  Escolher fileira\n← →  Trocar de coluna\nOK  Pegar e mover (coluna Fileira) · Remover, trocar card e tamanho nas outras\nVoltar  Fechar", "↑ ↓  Pick a row\n← →  Switch column\nOK  Grab and move (Row column) · Remove, change card and size in the others\nBack  Close" },
  { "↑ ↓  Escolher fileira · segure para pular por letra\nOK  Adicionar à Home (entra na fila se a Home estiver cheia)\n↑ no topo  Abas\nVoltar  Fechar", "↑ ↓  Pick a row · hold to jump by letter\nOK  Add to Home (queued if Home is full)\n↑ at the top  Tabs\nBack  Close" },
  { "↑ ↓  Mover a fileira\nOK  Soltar aqui\nVoltar  Cancelar o movimento", "↑ ↓  Move the row\nOK  Drop it here\nBack  Cancel the move" },
  { "↑ ↓  Mover a fileira\n← →  Mover o bloco do addon\nOK  Soltar aqui\nVoltar  Cancelar o movimento", "↑ ↓  Move the row\n← →  Move the add-on block\nOK  Drop it here\nBack  Cancel the move" },
  { "↑ ↓  Mover o bloco do addon\n← →  Mover so a fileira\nOK  Soltar aqui\nVoltar  Cancelar", "↑ ↓  Move the add-on block\n← →  Move just the row\nOK  Drop it here\nBack  Cancel" },
  { "↑ ↓  Navegar\nOK  Abrir\nVoltar  Ir para as categorias", "↑ ↓  Navigate\nOK  Open\nBack  Go to the categories" },
  { "↑ ↓  Navegar\n← →  Alterar valor\nVoltar  Ir para as categorias", "↑ ↓  Navigate\n← →  Change value\nBack  Go to the categories" },
  { "↑ ↓  rolar   ·   ← →  página   ·   OK  atualizar   ·   Voltar  fechar", "↑ ↓  scroll   ·   ← →  page   ·   OK  refresh   ·   Back  close" },
  { "↑ ↓ Escolher   ·   OK Confirmar", "↑ ↓ Choose   ·   OK Confirm" },
  { "↑ ↓ Navegar   OK Fechar   Voltar Fechar", "↑ ↓ Navigate   OK Close   Back Close" },
  { "↑ ↓ Navegar   OK Selecionar   Voltar Fechar", "↑ ↓ Navigate   OK Select   Back Close" },
  { "✓ Assistido%s%s", "✓ Watched%s%s" },
